apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: uppay
data:
  nginx.conf: |
    worker_processes auto;
    
    events {
        worker_connections 1024;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
    
        sendfile on;
        keepalive_timeout 65;
    
        server {
            listen 80;
            server_name localhost;
            root /usr/share/nginx/html/browser;
            index index.csr.html index.html;
            
            location / {
                try_files $uri $uri/ /index.csr.html;
            }
    
            # Handle static assets
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                expires max;
                add_header Cache-Control "public, no-transform";
                try_files $uri =404;
            }
    
            # Don't cache index.html
            location = /index.csr.html {
                add_header Cache-Control "no-cache, no-store, must-revalidate";
                add_header Pragma "no-cache";
                add_header Expires "0";
            }
    
            # API routes
            location /api/auth {
                proxy_pass http://a8e72f70f0d314895b5ddc9a9bdcf84f-1050400826.sa-east-1.elb.amazonaws.com;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
    
            location /api/fees {
                proxy_pass http://a3fedee11a61b4b239510a3493f51775-1326147047.sa-east-1.elb.amazonaws.com;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
    
            location /api/customer {
                proxy_pass http://a04a1302004754bd0b58164ff71a43ff-564480400.sa-east-1.elb.amazonaws.com;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
    
            location /api/loan {
                proxy_pass http://ac9808c3bf27a4fb685c1ecb93b3a464-1705769540.sa-east-1.elb.amazonaws.com;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }