apiVersion: v1
kind: Service
metadata:
  name: uppay-service
  namespace: uppay
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:sa-east-1:039074742130:certificate/b0d45f64-c51d-4a29-ba22-05e653694d24
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"  # Alterado de TCP para HTTP
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-2016-08"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  selector:
    app: uppay
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer